import React from "react";
import {
  SiTypescript, SiJavascript, SiPython,
  SiReact, SiNextdotjs, SiTailwindcss,
  SiNodedotjs, SiExpress, SiDjango,
  SiPostgresql, SiRedis, SiFirebase,
  SiDocker, SiGit,
  SiGo, SiReactquery, SiPrisma, SiRabbitmq,
  SiSentry, SiTurborepo, SiMinio,
  SiOpenai, SiGrafana, SiPrometheus,
} from "react-icons/si";
import { FaAws } from "react-icons/fa";

export const techIcons: Record<string, React.ElementType> = {
  "typescript": SiTypescript,
  "javascript": SiJavascript,
  "javascript (es6+)": SiJavascript,
  "python": SiPython,
  "go": SiGo,
  "sql": SiPostgresql,
  "react": SiReact,
  "next.js": SiNextdotjs,
  "tailwind": SiTailwindcss,
  "tailwind css": SiTailwindcss,
  "tanstack query": SiReactquery,
  "node.js": SiNodedotjs,
  "express": SiExpress,
  "django": SiDjango,
  "prisma orm": SiPrisma,
  "rabbitmq": SiRabbitmq,
  "postgresql": SiPostgresql,
  "redis": SiRedis,
  "firebase": SiFirebase,
  "docker": SiDocker,
  "aws": FaAws,
  "git": SiGit,
  "sentry": SiSentry,
  "turborepo": SiTurborepo,
  "minio (s3)": SiMinio,
  "llm orchestration": SiOpenai,
  "rag": SiOpenai,
  "vector search (pgvector)": SiPostgresql,
  "ai agents": SiOpenai,
  "grafana": SiGrafana,
  "prometheus": SiPrometheus,
};

export const techColors: Record<string, string> = {
  "typescript": "#3178C6",
  "javascript": "#F7DF1E",
  "javascript (es6+)": "#F7DF1E",
  "python": "#3776AB",
  "go": "#00ADD8",
  "sql": "#4479A1",
  "react": "#61DAFB",
  "next.js": "#000000",
  "tailwind": "#06B6D4",
  "tailwind css": "#06B6D4",
  "tanstack query": "#FF4154",
  "node.js": "#339933",
  "express": "#444444",
  "django": "#0C4B33",
  "prisma orm": "#2D3748",
  "rabbitmq": "#FF6600",
  "postgresql": "#4169E1",
  "redis": "#DC382D",
  "firebase": "#FFCA28",
  "docker": "#2496ED",
  "aws": "#FF9900",
  "git": "#F05032",
  "sentry": "#362D59",
  "turborepo": "#EF4444",
  "minio (s3)": "#C72E49",
  "llm orchestration": "#412991",
  "rag": "#4B5563",
  "vector search (pgvector)": "#336791",
  "ai agents": "#EF4444",
  "grafana": "#F46800",
  "prometheus": "#E6522C",
};

export const stack = [
  { label: "languages", items: ["javascript (es6+)", "typescript", "python", "sql", "go"] },
  { label: "frontend", items: ["react", "next.js", "tailwind css", "tanstack query"] },
  { label: "backend", items: ["node.js", "express", "django", "prisma orm", "rabbitmq"] },
  { label: "ai engineering", items: ["llm orchestration", "rag", "vector search (pgvector)", "ai agents"] },
  { label: "cloud & devops", items: ["docker", "postgresql", "redis", "minio (s3)", "sentry", "turborepo", "grafana", "prometheus"] },
];
