// Auto-generated by scripts/generate-post-map.mjs – do not edit
import cache_stampede from "./posts/cache_stampede.mdx";
import client_and_server_components_in_nextjs from "./posts/client_and_server_components_in_nextjs.mdx";
import custom_hooks_in_nextjs from "./posts/custom_hooks_in_nextjs.mdx";
import middleware_in_nextjs from "./posts/middleware_in_nextjs.mdx";
import nextjs_rendering_techniques_comprehensive_guide from "./posts/nextjs_rendering_techniques_comprehensive_guide.mdx";
import nginx_load_balancing_and_reverse_proxy from "./posts/nginx_load_balancing_and_reverse_proxy.mdx";
import seo_best_practices_for_both_nextjs_and_nodejs from "./posts/seo_best_practices_for_both_nextjs_and_nodejs.mdx";

import type { ComponentType } from "react";

export const postMap: Record<string, ComponentType> = {
  "cache_stampede": cache_stampede,
  "client_and_server_components_in_nextjs": client_and_server_components_in_nextjs,
  "custom_hooks_in_nextjs": custom_hooks_in_nextjs,
  "middleware_in_nextjs": middleware_in_nextjs,
  "nextjs_rendering_techniques_comprehensive_guide": nextjs_rendering_techniques_comprehensive_guide,
  "nginx_load_balancing_and_reverse_proxy": nginx_load_balancing_and_reverse_proxy,
  "seo_best_practices_for_both_nextjs_and_nodejs": seo_best_practices_for_both_nextjs_and_nodejs,
};

export const postSlugs = ["cache_stampede","client_and_server_components_in_nextjs","custom_hooks_in_nextjs","middleware_in_nextjs","nextjs_rendering_techniques_comprehensive_guide","nginx_load_balancing_and_reverse_proxy","seo_best_practices_for_both_nextjs_and_nodejs"] as const;
